---
kind: Service
apiVersion: v1
metadata:
  name: jbaskeen
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-algorithm: "round_robin"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "14b8293c-8ac1-4655-a2c3-e004730a0514"
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
spec:
  type: LoadBalancer
  selector:
    app: jbaskeen
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jbaskeen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jbaskeen
  template:
    metadata:
      labels:
        app: jbaskeen
    spec:
      containers:
      - name: nginx
        image: registry.digitalocean.com/skeezy/jbaskeen:latest
        ports:
        - containerPort: 80
          protocol: TCP
